"""Add cascade delete to session_cart when product deleted

Revision ID: 2d1196a7cf82
Revises: ed26fe8a9ffd
Create Date: 2025-10-15 14:21:48.833256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1196a7cf82'
down_revision: Union[str, Sequence[str], None] = 'ed26fe8a9ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_cart_product_id_fkey', 'session_cart', type_='foreignkey')
    op.create_foreign_key(None, 'session_cart', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_cart', type_='foreignkey')
    op.create_foreign_key('session_cart_product_id_fkey', 'session_cart', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
